name: Project Healer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly check
  workflow_dispatch:     # Manual trigger

jobs:
  heal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Scan for issues
        id: scan
        run: node src/index.js scan --report
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Scan for vulnerabilities
        id: vuln-scan
        run: node src/index.js security-scan --report
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Apply fixes
        id: fix
        if: ${{ steps.scan.outputs.issues_found == 'true' || steps.vuln-scan.outputs.vulnerabilities_found == 'true' }}
        run: node src/index.js heal --all
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Create Pull Request with fixes
        if: ${{ steps.fix.outputs.fixes_applied == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "🩹 Automated fixes by Project Healer"
          title: "Self-Healing: Automated Fixes"
          body: |
            This PR contains automated fixes applied by the Self-Heal Project Healer.
            
            ## Changes Applied
            ${{ steps.fix.outputs.fixes_summary }}
            
            ## Vulnerability Fixes
            ${{ steps.vuln-scan.outputs.vulnerabilities_summary }}
            
            Please review these changes carefully before merging.
          branch: auto-heal-${{ github.run_id }}
          delete-branch: true
          
      - name: Upload scan report
        uses: actions/upload-artifact@v3
        with:
          name: healing-reports
          path: |
            reports/issues-report.md
            reports/security-report.md
            reports/fix-report.md

  learn:
    needs: heal
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Download healing reports
        uses: actions/download-artifact@v3
        with:
          name: healing-reports
          path: reports/
      
      - name: Learn from applied fixes
        run: node src/index.js learn --from-reports
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Commit new patterns
        uses: EndBug/add-and-commit@v9
        with:
          add: 'patterns/'
          author_name: 'Project Healer'
          author_email: 'project-healer@noreply.github.com'
          message: '📚 Update healing patterns based on learning'
          push: true
