name: Project Healer

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # Weekly check
  workflow_dispatch:     # Manual trigger

jobs:
  heal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Scan and Heal
        run: npm run healer -- --fix --report --graph
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        
      - name: Upload dependency graph
        uses: actions/upload-artifact@v2
        with:
          name: dependency-graph
          path: healer-report/dependency-graph.html
        
      - name: Commit Fixes
        if: env.FIXES_APPLIED == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "🩹 Automated fixes by Project Healer"
          title: "Self-Healing: Automated Fixes"
          branch: auto-heal-${{ github.run_id }}